name: QA
on:
  workflow_call:

jobs:
  qa:
    name: QA
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    timeout-minutes: 3
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: npm ci
      - name: Type Check
        run: npx tsc
      # - name: Lint Check
      #   run: npx one
      - name: Run tests
        run: npm test
