name: Deploy to production
on: workflow_dispatch

jobs:
  qa:
    uses: sajmoni/foo/.github/workflows/qa.yml@main
  build:
    name: Build game
    needs: qa
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    timeout-minutes: 3
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: npm ci --production
      - name: Build
        run: npm run build
      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: game
          path: dist
  deploy:
    name: Deploy game
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Download build
        uses: actions/download-artifact@v1
        with:
          name: game
      - name: Install Butler
        run: |
          curl --max-time 5 -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip
          chmod +x butler
          ./butler -V
      - name: Deploy to itch.io
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
        run: ./butler push game sajmoni/foo:web
  tag:
    name: Tag release and generate release notes
    needs: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install auto-changelog
        run: npm install auto-changelog --no-save
      - name: Set git information
        run: |
          git config --global user.name 'Github Actions [bot]'
          git config --global user.email 'github-actions@not-a-real-email.com'
      - name: Increase version and create release notes
        run: npm version patch
      - name: Push back to repository
        run: |
          git push origin --tags
          git push
