extends: airbnb-base
env:
  browser: true
rules:
  # Enables typescript not reporting extended objects as errors
  dot-notation: off
  # These two rules interfere with Parcel absolute imports
  import/no-absolute-path: off
  import/no-unresolved: off
  no-use-before-define: off
  semi:
    - error
    - never
