name: QA
on: workflow_call

env:
  NODE_VERSION: 20

jobs:
  qa:
    name: QA
    runs-on: ubuntu-latest
    timeout-minutes: 4
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Use Node.js $NODE_VERSION
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: npm ci
      - name: Type Check
        run: npx tsc --noEmit
      # - name: Lint Check
      #   run: npx one
      - name: Run tests
        run: npm test
